// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_middleware from "./routes/_middleware.ts";
import * as $authenticate_index from "./routes/authenticate/index.ts";
import * as $groups_id_disable from "./routes/groups/[id]/disable.ts";
import * as $groups_id_enable from "./routes/groups/[id]/enable.ts";
import * as $groups_id_index from "./routes/groups/[id]/index.ts";
import * as $groups_index from "./routes/groups/index.ts";
import * as $users_id_index from "./routes/users/[id]/index.ts";
import * as $users_index from "./routes/users/index.ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $_middleware,
    "./routes/authenticate/index.ts": $authenticate_index,
    "./routes/groups/[id]/disable.ts": $groups_id_disable,
    "./routes/groups/[id]/enable.ts": $groups_id_enable,
    "./routes/groups/[id]/index.ts": $groups_id_index,
    "./routes/groups/index.ts": $groups_index,
    "./routes/users/[id]/index.ts": $users_id_index,
    "./routes/users/index.ts": $users_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
